package pz.pacman.constants;

public enum EngineEventType {
	START_NEW_GAME, PAUSE_GAME, RESUME_GAME, GAME_OVER, ABANDON_GAME, GAME_COMPLETE,
	LEVEL_COMPLETE, LOAD_NEXT_LEVEL, RESUME_SAVED_GAME,
	MOVE_ELEMENS,
	PACMAN_MOVE_UP, PACMAN_MOVE_DOWN, PACMAN_MOVE_LEFT,	PACMAN_MOVE_RIGHT, 
	INC_GAME_TIME, REVERT_PACMAN, BONUS_DOT_DESTROY, SHUFFLE_DOT;
}
